# -*- coding: utf-8 -*-
"""Projeto Elaborado para curso.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E3ZcPoWEBGVOadyr_lOo_alocuSNU9Ya
"""

# Importando as bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("ggplot")

# Uplod do arquivo
from google.colab import files
arq = files.upload()

# Criando nosso Dataframe
df = pd.read_excel("Dadosplantioflorestal.xlsx")

df.head()

# Verificando os tipos de dados
df.dtypes

# Qual o lucro total dos 4 plantios por área?
df["Lucro"] = df["Receitaha"] - df["Customudasha"]

df.head()

# Total de varas produzidas pelos 4 plantios por hectare.
round(df["Nvarasha"].sum(),2)

# Custo total dos 4 plantios
round(df["Customudasha"].sum(),2)

# Lucro total dos 4 plantios
round(df["Lucro"].sum(),2)

# Grafico para verificar a produção de Varas por hectare nos 4 plantios.
plt.bar(df["Plantios"],df["Nvarasha"], color="green")
plt.xlabel("Plantios")
plt.ylabel("Número de varas por hectare");

# Grafico em pizza para verificar em porcentagema produção de Varas por hectare nos 4 plantios.
explode = (0.1,0,0,0)
plt.pie(df["Nvarasha"], labels=df["Plantios"], autopct= '%1.1f""', shadow=True, explode=explode)
plt.axis('equal');

# Grafico para verificar o custo para implantar cada plantio
plt.bar(df["Plantios"],df["Customudasha"], color="blue")
plt.xlabel("Plantios")
plt.ylabel("Custo de produção por hectare");

# Grafico para verificar o lucro total por plantio
plt.bar(df["Plantios"],df["Lucro"], color="coral")
plt.xlabel("Plantios")
plt.ylabel("Lucro por hectare");

